### ISSUE TITLE
feature request: comments

### ISSUE THREAD

**Issue by sthen** [jasperla/portroach#14]
If you're bored sometime! It would be nice to be able to add a PORTROACH_COMMENT tag to the port Makefile and have it show up as an additional column in the report. For use when there's a specific reason why you have been slacking on the update and want an easy place to make a note of it :-)

**Comment by jasperla** [comment]
Sounds like a good idea actually.

**Comment by jasperla** [comment]
This has been implemented as part of portroach 2.0.4 and should be included in the generated pages shortly. Thanks!
