### ISSUE TITLE
portroach doesn't detect new versions in bitbucket (again)

### ISSUE THREAD

**Issue by juanfra684** [jasperla/portroach#17]
`graphics/pdf2djvu` has available a new version but portroach doesn't detect it. The version actual is `0.8.1` and the update is `0.8.2`.

**Comment by jasperla** [comment]
While this particular port isn't hosted on BitBucket anymore, with 1921d3e45a030aceb63f70f5ae79d3d80b9d9736 I've fixed the site handler to detect new releases for a number of other ports which are on BitBuclet.
