### ISSUE TITLE
github versioncmp problem

### ISSUE THREAD

**Issue by sthen** [jasperla/portroach#23]
Some of the github things don't pick up new versions, e.g. https://github.com/nghttp2/nghttp2/releases, https://github.com/kovidgoyal/calibre/releases. Notably these have proper uploaded tarballs rather than just autogenerated ones.

**Comment by juanfra684** [comment]
Works for me with aria2 (same author as nghttp2). The OpenBSD package and portroach.o.o are outdated.

**Comment by jasperla** [comment]
This should be fixed with 8e73dd5cd75902eeab6cfe19e71ef536f7c7e08e . Some other GitHub oddities should also have been addressed by this and subsequent commits.
