### ISSUE TITLE
get_iplayer uses "latest" instead of a version

### ISSUE THREAD

**Issue by sthen** [jasperla/portroach#8]
The current version of get_iplayer is 2.87 but portroach picks it up as "latest". It's probably looking at the github releases page which in this case has a "latest release" pointer for 2.87, which seems uncommon for most github projects.

**Comment by jasperla** [comment]
It seems this issue has now been fixed after I've rewritten the GitHub site handler. Can you confirm this?

**Comment by sthen** [comment]
Now working.
